# ----------------------------------------------------- 
# VARIÁVEIS DE PROGRAMAS GLOBAIS
# ----------------------------------------------------- 
$terminal = kitty
$fileManager = kitty yazi
$menu = fuzzel
$browser = firefox

# ----------------------------------------------------- 
# SERVIÇOS DE INICIALIZAÇÃO (AUTOSTART)
# ----------------------------------------------------- 
# Sistema
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

# Área de Transferência (Clipboard)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Daemons e Scripts (Segurança e Interface)
exec-once = ~/.config/hypr/scripts/battery_alert.sh &
exec-once = hypridle &
exec-once = waybar &
exec-once = mako &
exec-once = awww-daemon &
