# ----------------------------------------------------- 
# VARIÁVEIS DE AMBIENTE (WAYLAND & THEMES)
# ----------------------------------------------------- 

# Tamanho do Cursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Correção para Java (Para os apps da faculdade rodarem lisos)
env = _JAVA_AWT_WM_NONREPARENTING,1

# Forçar Wayland nativo nos apps
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1

# Tema e Interface
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_QPA_PLATFORMTHEME,qt6ct
