# ----------------------------------------------------- 
# DISPOSITIVOS DE ENTRADA (TECLADO E MOUSE)
# ----------------------------------------------------- 
input {
    kb_layout = br, us
    kb_variant = , intl
    kb_model =
    kb_options = grp:alt_space_toggle
    kb_rules =

    follow_mouse = 1
    sensitivity = 0 

    touchpad {
        natural_scroll = true
        tap-to-click = true
        drag_lock = true
        disable_while_typing = true
    }

    touchdevice {
        transform = 0
    }
}

# ----------------------------------------------------- 
# GESTOS DO TOUCHPAD
# ----------------------------------------------------- 
# Deslizar para os lados: Troca de Workspace
gesture = 3, horizontal, workspace

# Deslizar para baixo: Fecha janela atual
gesture = 3, down, close

# Deslizar para cima: Fullscreen
gesture = 3, up, fullscreen

# Deslizar 4 dedos: Deixa a janela flutuante
gesture = 4, horizontal, float
