# ----------------------------------------------------- 
# REGRAS GERAIS DE JANELAS
# ----------------------------------------------------- 

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# ----------------------------------------------------- 
# REGRAS PARA APLICATIVOS TUI FLUTUANTES 
# ----------------------------------------------------- 

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = pavucontrol-center
    match:class = org.pulseaudio.pavucontrol
    float = true
    size = 700 450
    center = true
}

windowrule {
    name = nvtop-center
    match:class = floating_nvtop
    float = true
    size = 1000 700
    center = true
}

windowrule {
    name = nmtui-center
    match:class = floating_nmtui
    float = true
    size = 700 500
    center = true
}

windowrule {
    name = btop-center
    match:class = floating_btop
    float = true
    size = 1000 700
    center = true
}

# ----------------------------------------------------- 
# REGRA PARA VS CODE TRANSLÚCIDO
# ----------------------------------------------------- 
windowrule {
    name = vscode-opacity
    match:class = ^(code-oss|code)$
    opacity = 0.8
}
