general {
    lock_cmd = pidof hyprlock || hyprlock       # Comando para trancar
    before_sleep_cmd = loginctl lock-session    # Tranca antes de suspender
    after_sleep_cmd = hyprctl dispatch dpms on  # Liga a tela ao voltar
}

listener {
    timeout = 150                                # 2.5 min
    on-timeout = brightnessctl set 10%           # Diminui o brilho
    on-resume = brightnessctl set 100%           # Volta o brilho
}

listener {
    timeout = 300                                # 5 min
    on-timeout = loginctl lock-session           # Tranca a tela
}

listener {
    timeout = 600                                # 10 min
    on-timeout = hyprctl dispatch dpms off       # Desliga o monitor
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 900                                # 15 min
    on-timeout = systemctl suspend               # Suspende o notebook
}
