# #######################################################################################
# MEU HYPRLAND MODULAR - CATPPUCCIN MACCHIATO
# #######################################################################################

# Carrega os módulos de configuração
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/theme.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf
